### ISSUE TITLE
How to config options when using Python binding

### ISSUE THREAD

**Issue by KienPM** [coccoc/coccoc-tokenizer#10]
This is a great project!
Can you please provide document guiding how to use options such as -t, -u... when using Python binding?
Thank you so much!

**Comment by bachan** [comment]
Python bindinging don't define needed constants at the moment, so a quick solution for -u would be:
```
from CocCocTokenizer import PyTokenizer
t = PyTokenizer()
res = t.word_tokenize(text, 2)
```

And for -n the quick solution would be:
```
from CocCocTokenizer import PyTokenizer
t = PyTokenizer(False)
res = t.word_tokenize(text)
```

**Comment by bachan** [comment]
For more proper solution feel free to fix python extension code (.pyx file) and send us a pull request, we will happily review and include it.

**Comment by KienPM** [comment]
Thanks for your answer!
