### ISSUE TITLE
use lib for python

### ISSUE THREAD

**Issue by quanghuynguyen1902** [coccoc/coccoc-tokenizer#12]
mình đã cài xong phần 

```python
$ mkdir build && cd build
$ cmake -DBUILD_PYTHON=1 ..
# make install
```
nhưng mình vẫn chưa sử dụng được 
```python
from CocCocTokenizer import PyTokenizer
```

**Comment by anhducle98** [comment]
Make sure your `sys.path` contains the path in which you install the library.
```python
import sys
print(sys.path)
```

If you don't see the installed path, you can alter the environment variable `PYTHONPATH` to include it, for example:
```bash
$ PYTHONPATH=/usr/local/lib/python3.8 python
```

**Comment by michaelLampard** [comment]
> mình đã cài xong phần
> 
> ```python
> $ mkdir build && cd build
> $ cmake -DBUILD_PYTHON=1 ..
> # make install
> ```
> 
> nhưng mình vẫn chưa sử dụng được
> 
> ```python
> from CocCocTokenizer import PyTokenizer
> ```

em cũng gặp lỗi này nhưng chưa fix được, anh đã fix được chưa ạ?

**Comment by michaelLampard** [comment]
@anhducle98 in my case:
- Environment: Ubuntu server 18.04
- Install:
`apt install python3-pip`
`pip3 install Cython --install-option="--no-cython-compile"`
`cmake -DBUILD_PYTHON=1 ..`
`make install`

Output:
`...
-- Installing: /usr/local/share/tokenizer/dicts/syllable_trie.dump
-- Installing: /usr/local/share/tokenizer/dicts/nontone_pair_freq_map.dump
-- Up-to-date: /usr/local/lib
-- Up-to-date: /usr/local/lib/python3.6
-- Installing: /usr/local/lib/python3.6/site-packages
-- Installing: /usr/local/lib/python3.6/site-packages/CocCocTokenizer.cpython-36m-x86_64-linux-gnu.so
-- Installing: /usr/local/lib/python3.6/site-packages/CocCocTokenizer-1.4-py3.6.egg-info`

- Testing:
`tokenizer "Từng bước để trở thành một lập trình viên giỏi"`

- Python:
>>> import sys
>>> print(sys.path)
['', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages']

But when i use python binding with root user:
>>> from CocCocTokenizer import PyTokenizer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'CocCocTokenizer'

Help me, please!
