### ISSUE TITLE
Khi build trên Windows với tham số -DBUILD_PYTHON=1 bị lỗi

### ISSUE THREAD

**Issue by tuphampro** [coccoc/coccoc-tokenizer#16]
Khi build trên Windows với tham số -DBUILD_PYTHON=1 thì mình gặp lỗi như sau:
![image](https://user-images.githubusercontent.com/19162524/99623972-da708900-2a5f-11eb-8c95-29005b48c8ae.png)
![image](https://user-images.githubusercontent.com/19162524/99623977-dd6b7980-2a5f-11eb-8fb6-09efc449ce42.png)

**Comment by bachan** [comment]
Sorry for late response.

It's hard to understand from the screenshot, which file was missing, but it's clearly an issue with your build environment. If you still encounter this error, please, reopen the issue and provide full build output.
