### ISSUE TITLE
lỗi khi chạy bằng c++ trên window

### ISSUE THREAD

**Issue by trongvanhpkt99** [coccoc/coccoc-tokenizer#17]
![image](https://user-images.githubusercontent.com/45105226/102874489-18a10400-4475-11eb-8e5b-92186609eddb.png)
Khi chạy bằng c++ mình gặp lỗi này
bạn thử demo giúp mình tokenizer trên c hoặc c++ được ko ạ?

**Comment by manhnt9** [comment]
Try not using special characters in your path name. You have `D:\Van\C++\...`
