### ISSUE TITLE
java.lang.RuntimeException: Cannot initialize Tokenizer

### ISSUE THREAD

**Issue by namnam3000** [coccoc/coccoc-tokenizer#18]
![Screenshot from 2021-03-17 09-29-10](https://user-images.githubusercontent.com/51730208/111405558-4a87d680-8703-11eb-870a-9d757453726d.png)

mình đã build libs java. nhưng khi sử dụng thì gặp lỗi này

**Comment by anhducle98** [comment]
Nguyên nhân là vì hằng `dictPath` trong class `Tokenizer` được đặt là `/usr/share/tokenizer/dicts`.
Tạm thời bạn có thể sửa lại thành đường dẫn chứa các file từ điển mà bạn đã install.

**Comment by deathghost** [comment]
> Nguyên nhân là vì hằng `dictPath` trong class `Tokenizer` được đặt là `/usr/share/tokenizer/dicts`.
> Tạm thời bạn có thể sửa lại thành đường dẫn chứa các file từ điển mà bạn đã install.

Do mặc định khi install tất cả sẽ theo prefix path là `/usr/local`. Có thể rebuild lại bằng cách bổ sung thêm tham số `cmake -DBUILD_JAVA=1 -DCMAKE_INSTALL_PREFIX=/usr ..` và `make install` thì sẽ hết lỗi
