### ISSUE TITLE
Lỗi khi build project trên Ubuntu

### ISSUE THREAD

**Issue by seta-hainguyen** [coccoc/coccoc-tokenizer#20]
Mình gặp lỗi này khi chạy `make install` trên Ubuntu 20.04:

CMake Error at cmake_install.cmake:105 (file):
  file INSTALL cannot make directory "/usr/local/share/tokenizer/dicts_text":
  No such file or directory.

make: *** [Makefile:74: install] Error 1

**Comment by knst** [comment]
Probably, you need in `sudo` permission
