### ISSUE TITLE
Can the tokenizer produce tokens as original case?

### ISSUE THREAD

**Issue by duydo** [coccoc/coccoc-tokenizer#24]
I've been using coccoc-tokenizer Java bindings for Vietnamese Elasticsearch analysis plugin, we want to keep tokens as original cases. For example, text  "Cộng hòa Xã hội chủ nghĩa Việt Nam" will be tokenized as `cộng_hòa xã_hội chủ_nghĩa việt_nam`,
what we expect is `Cộng_hòa Xã_hội chủ_nghĩa Việt_Nam`. 

Can we somehow make the tokenizer produce tokens as original cases?

**Comment by anhducle98** [comment]
Yes it is certainly possible.
See similar issue here: https://github.com/coccoc/coccoc-tokenizer/issues/11
Later I will check on how to adding this feature mergable to master.

**Comment by duydo** [comment]
@anhducle98 Thanks so much for your supports. I've just made it work for the plugin https://github.com/duydo/elasticsearch-analysis-vietnamese/blob/03b285c682d8499a7c13f5e7496a7d0421381b6a/src/main/java/com/coccoc/Tokenizer.java#L100
