### ISSUE TITLE
Need help when install libary for python in conda environment

### ISSUE THREAD

**Issue by LittleCuteBug** [coccoc/coccoc-tokenizer#25]
Dear all,
I've some issues when trying to install the CocCocTokenizer library for python 3.8 in a conda environment.
I've tried:
- activate the conda environment before building with Cmake
```
git clone git@github.com:coccoc/coccoc-tokenizer.git
cd coccoc-tokenizer/
mkdir build && cd build
conda activate py3.8
sudo  cmake -DBUILD_JAVA=1 -DBUILD_PYTHON=1 ..
sudo make install
```
- using DCMAKE_INSTALL_PREFIX flag and point it to site-packages directory
```
sudo  cmake -DBUILD_JAVA=1 -DBUILD_PYTHON=1 -DCMAKE_INSTALL_PREFIX=/home/huyqnguyen/anaconda3/envs/py3.8 ..
```
- insert `conda activate py3.8` to the `/python/build_python.sh` file

but none of those solutions help me to include the coccoctokenizer in python:
```
from CocCocTokenizer import PyTokenizer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'PyTokenizer' from 'CocCocTokenizer' (unknown location)
```

**Comment by anhducle98** [comment]
You can try install the files manually to your python env site-packages:

```bash
$ cp build/python/lib/python3.10/site-packages/CocCocTokenizer.* /home/huyqnguyen/anaconda3/envs/py3.8/lib/python3.8/site-packages
```

**Comment by LittleCuteBug** [comment]
Dear @anhducle98, thanks for your suggestion, but after I tried to copy the file `CocCocTokenizer-1.4-py3.8-linux-x86_64.egg` in the directory `coccoc-tokenizer/build/python/lib/python3.8/site-packages/` to the python env site-packages `/home/huyqnguyen/anaconda3/envs/py3.8/lib/python3.8/site-packages/` but it's still not work. I've also tried rename the directory to  `CocCocTokenizer.egg` and it's not work too.

**Comment by anhducle98** [comment]
Sorry. I meant copying the .so and .py files:
```
$ cp build/python/lib/python3.8/site-packages/CocCocTokenizer-1.4-py3.8-linux-x86_64.egg/CocCocTokenizer.* /home/huyqnguyen/anaconda3/envs/py3.8/lib/python3.8/site-packages/
```

**Comment by LittleCuteBug** [comment]
Thanks for your support, it works beautifully, I'll close this issue now
